name: Build and Push Docker Image

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      ZTM_VERSION:
        description: 'Version of ZTM'
        required: true
        default: '0.0.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract ZTM_VERSION input
        id: extract-version
        run: echo "ZTM_VERSION=${{ github.event.inputs.ZTM_VERSION }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: addozhang/ztm:${{ env.ZTM_VERSION }}
          build-args: |
            ZTM_VERSION=${{ env.ZTM_VERSION }}

      - name: Pull the Docker image for amd64
        run: docker pull addozhang/ztm:${{ env.ZTM_VERSION }} --platform amd64

      - name: Save Docker image to tar file for amd64
        run: docker save addozhang/ztm:${{ env.ZTM_VERSION }} -o ztm_${{ env.ZTM_VERSION }}_amd64.tar

      - name: Upload Docker image tar file for amd64
        uses: actions/upload-artifact@v3
        with:
          name: ztm_${{ env.ZTM_VERSION }}_amd64.tar
          path: ztm_${{ env.ZTM_VERSION }}_amd64.tar

      - name: Pull the Docker image for arm64
        run: docker pull addozhang/ztm:${{ env.ZTM_VERSION }} --platform 

      - name: Save Docker image to tar file for arm64
        run: docker save addozhang/ztm:${{ env.ZTM_VERSION }} -o ztm_${{ env.ZTM_VERSION }}_arm64.tar

      - name: Upload Docker image tar file for arm64
        uses: actions/upload-artifact@v3
        with:
          name: ztm_${{ env.ZTM_VERSION }}_arm64.tar
          path: ztm_${{ env.ZTM_VERSION }}_arm64.tar

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ env.ZTM_VERSION }}
          release_name: v${{ env.ZTM_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Docker image tar files to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ztm_${{ env.ZTM_VERSION }}_amd64.tar
          asset_name: ztm_${{ env.ZTM_VERSION }}_amd64.tar
          asset_content_type: application/octet-stream

      - name: Upload Docker image tar files to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ztm_${{ env.ZTM_VERSION }}_arm64.tar
          asset_name: ztm_${{ env.ZTM_VERSION }}_arm64.tar
          asset_content_type: application/octet-stream
